# Generated by Django 3.2.5 on 2022-04-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentAcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AcademicYear', models.IntegerField()),
            ],
            options={
                'db_table': 'CurrentAcademicYear',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MakeupSummaryStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubName', models.CharField(max_length=100)),
                ('SubCode', models.CharField(max_length=10)),
                ('Dept', models.IntegerField()),
                ('Regulation', models.IntegerField()),
                ('BYear', models.IntegerField()),
                ('Passed', models.IntegerField()),
                ('Failed', models.IntegerField()),
                ('Total', models.IntegerField()),
            ],
            options={
                'db_table': 'MakeupSummaryStatsV',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProgrammeModel',
            fields=[
                ('PID', models.IntegerField(primary_key=True, serialize=False)),
                ('ProgrammeName', models.CharField(max_length=20)),
                ('ProgrammeType', models.CharField(max_length=10)),
                ('Specialization', models.CharField(max_length=100)),
                ('Dept', models.IntegerField()),
            ],
            options={
                'db_table': 'Departments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistrationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AYear', models.IntegerField()),
                ('ASem', models.IntegerField()),
                ('BYear', models.IntegerField()),
                ('BSem', models.IntegerField()),
                ('Dept', models.IntegerField()),
                ('Mode', models.CharField(max_length=1)),
                ('Status', models.IntegerField()),
            ],
            options={
                'db_table': 'RegistrationStatus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegNo', models.IntegerField()),
                ('RollNo', models.IntegerField()),
                ('Name', models.CharField(max_length=70)),
            ],
            options={
                'db_table': 'StudentInfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentMakeupBacklogsVsRegistrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegNo', models.IntegerField()),
                ('RollNo', models.IntegerField()),
                ('Name', models.CharField(max_length=70)),
                ('BYear', models.IntegerField()),
                ('BSem', models.IntegerField()),
                ('Dept', models.IntegerField()),
                ('MakeupSubjects', models.CharField(max_length=300)),
                ('RegisteredSubjects', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'StudentMakeupBacklogsVsRegistrationsV',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentRegistrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegNo', models.IntegerField()),
                ('SubCode', models.CharField(max_length=10)),
                ('AYear', models.IntegerField()),
                ('ASem', models.IntegerField()),
                ('OfferedYear', models.IntegerField()),
                ('Dept', models.IntegerField()),
                ('BYear', models.IntegerField()),
                ('Regulation', models.IntegerField()),
                ('BSem', models.IntegerField()),
                ('Mode', models.IntegerField()),
            ],
            options={
                'db_table': 'StudentRegistrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentBacklogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegNo', models.IntegerField()),
                ('RollNo', models.IntegerField()),
                ('SubCode', models.CharField(max_length=10)),
                ('SubName', models.CharField(max_length=50)),
                ('OfferedYear', models.IntegerField()),
                ('Dept', models.IntegerField()),
                ('Credits', models.IntegerField()),
                ('BYear', models.IntegerField()),
                ('BSem', models.IntegerField()),
                ('Grade', models.CharField(max_length=2)),
                ('Regulation', models.IntegerField()),
                ('AYASBYBS', models.IntegerField()),
            ],
        ),
    ]
