# Generated by Django 3.2.5 on 2022-04-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDBRegistrations', '0001_initial'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Subjects_Staging',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('SubCode', models.CharField(max_length=10)),
        #         ('SubName', models.CharField(max_length=100)),
        #         ('BYear', models.IntegerField()),
        #         ('BSem', models.IntegerField()),
        #         ('Dept', models.IntegerField()),
        #         ('OfferedYear', models.IntegerField()),
        #         ('Regulation', models.IntegerField()),
        #         ('Creditable', models.IntegerField()),
        #         ('Credits', models.IntegerField()),
        #         ('Type', models.CharField(max_length=10)),
        #         ('Category', models.CharField(max_length=10)),
        #     ],
        #     options={
        #         'db_table': 'Subjects_Staging',
        #         'managed': False,
        #     },
        # ),
        migrations.AlterModelOptions(
            name='studentbacklogs',
            options={'managed': False},
        ),
    ]
