# Generated by Django 3.2.5 on 2022-04-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDBRegistrations', '0004_auto_20220426_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegNo', models.IntegerField()),
                ('AYear', models.IntegerField()),
                ('ASem', models.IntegerField()),
                ('SubCode', models.CharField(max_length=10)),
                ('OfferedYear', models.IntegerField()),
                ('Dept', models.IntegerField()),
                ('Regulation', models.IntegerField()),
                ('Grade', models.CharField(max_length=2)),
                ('AttGrade', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'StudentGrades',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='studentcancellation',
            name='AttGrade',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
