# Generated by Django 3.2.5 on 2022-04-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDBRegistrations', '0005_auto_20220426_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotPromoted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AYear', models.IntegerField()),
                ('BYear', models.IntegerField()),
                ('RegNo', models.IntegerField()),
                ('PoA', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'NotPromoted',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentGradePoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegNo', models.IntegerField()),
                ('SubCode', models.CharField(max_length=10)),
                ('SubName', models.CharField(max_length=100)),
                ('BYear', models.IntegerField()),
                ('BSem', models.IntegerField()),
                ('Grade', models.CharField(max_length=2)),
                ('Credits', models.IntegerField()),
                ('AYASBYBS', models.IntegerField()),
                ('Type', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'StudentGradePointsMV',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CancelledStudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegNo', models.IntegerField()),
                ('RollNo', models.IntegerField()),
                ('Name', models.CharField(max_length=70)),
                ('Regulation', models.IntegerField()),
                ('Dept', models.IntegerField()),
                ('Gender', models.CharField(max_length=10)),
                ('Category', models.CharField(max_length=20)),
                ('GaurdianName', models.CharField(max_length=50)),
                ('Phone', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('Address1', models.CharField(max_length=150)),
                ('Address2', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'CancelledStudentInfo',
                'managed': True,
            },
        ),
    ]
