# Generated by Django 3.2.5 on 2022-04-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDBRegistrations', '0006_cancelledstudentinfo_notpromoted_studentgradepoints'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchChanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegNo', models.IntegerField()),
                ('RollNo', models.IntegerField()),
                ('CurrentDept', models.IntegerField()),
                ('NewDept', models.IntegerField()),
                ('AYear', models.IntegerField()),
            ],
            options={
                'managed': True,
            },
        ),
    ]
