# Generated by Django 3.2.5 on 2022-04-28 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDBRegistrations', '0007_branchchanges'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='branchchanges',
            table='BranchChanges',
        ),
    ]
