# Generated by Django 3.2.5 on 2022-04-30 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDBRegistrations', '0008_alter_branchchanges_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularRegistrationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegNo', models.IntegerField()),
                ('RollNo', models.IntegerField()),
                ('Name', models.CharField(max_length=70)),
                ('AYear', models.IntegerField()),
                ('ASem', models.IntegerField()),
                ('RegisteredSubjects', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'RegularRegistrationSummaryV',
                'managed': False,
            },
        ),
    ]
