# Generated by Django 4.0.4 on 2022-05-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDBRegistrations', '0009_regularregistrationsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacklogRegistrationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegNo', models.IntegerField()),
                ('RollNo', models.IntegerField()),
                ('Name', models.CharField(max_length=70)),
                ('AYear', models.IntegerField()),
                ('ASem', models.IntegerField()),
                ('Dept', models.IntegerField()),
                ('RegisteredSubjects', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'BacklogRegistrationSummaryV',
                'managed': False,
            },
        ),
    ]
