# Generated by Django 4.0.4 on 2022-05-21 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDBRegistrations', '0011_rolllists_alter_registrationstatus_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolllists',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='rolllists',
            table='RollLists',
        ),
    ]
