# Generated by Django 4.0.4 on 2022-05-21 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDBRegistrations', '0012_alter_rolllists_options_alter_rolllists_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolllists',
            options={'managed': False},
        ),
    ]
