# Generated by Django 4.0.4 on 2022-05-21 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDBRegistrations', '0013_alter_rolllists_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RollLists',
        ),
    ]
