# Generated by Django 4.0.4 on 2022-05-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDBRegistrations', '0015_rolllists'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegistrations_Staging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegNo', models.IntegerField()),
                ('AYear', models.IntegerField()),
                ('ASem', models.IntegerField()),
                ('BYear', models.IntegerField()),
                ('Mode', models.IntegerField()),
                ('sub_id', models.IntegerField()),
            ],
            options={
                'db_table': 'StudentRegistrations_Staging',
                'managed': False,
            },
        ),
    ]
