# Generated by Django 4.0.4 on 2022-05-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDBRegistrations', '0017_regulation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubCode', models.CharField(max_length=10)),
                ('SubName', models.CharField(max_length=100)),
                ('Creditable', models.IntegerField()),
                ('Credits', models.IntegerField()),
                ('Type', models.CharField(max_length=10)),
                ('Category', models.CharField(max_length=10)),
                ('RegEventId', models.IntegerField()),
            ],
            options={
                'db_table': 'Subjects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subjects_Staging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubCode', models.CharField(max_length=10)),
                ('SubName', models.CharField(max_length=100)),
                ('Creditable', models.IntegerField()),
                ('Credits', models.IntegerField()),
                ('Type', models.CharField(max_length=10)),
                ('Category', models.CharField(max_length=10)),
                ('RegEventId', models.IntegerField()),
            ],
            options={
                'db_table': 'Subjects_Staging',
                'managed': False,
            },
        ),
    ]
