# Generated by Django 4.0.4 on 2022-05-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDBRegistrations', '0018_subjects_subjects_staging'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Phone', models.IntegerField()),
                ('Email', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'FacultyInfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubjectFacultyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubId', models.IntegerField()),
                ('Section', models.CharField(max_length=10)),
                ('FacultyId', models.IntegerField()),
            ],
            options={
                'db_table': 'SubjectFacultyInfo',
                'managed': False,
            },
        ),
    ]
