# Generated by Django 4.0.4 on 2022-05-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDBRegistrations', '0019_facultyinfo_subjectfacultyinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DroppedRegularCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegNo', models.IntegerField()),
                ('sub_id', models.IntegerField()),
            ],
            options={
                'db_table': 'DroppedRegularCourses',
                'managed': False,
            },
        ),
    ]
