# Generated by Django 4.0.4 on 2022-05-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDBRegistrations', '0020_droppedregularcourses'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGrades_Staging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regid', models.IntegerField()),
                ('Regulation', models.IntegerField()),
                ('Grade', models.CharField(max_length=2)),
                ('AttGrade', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'StudentGrades_Staging',
                'managed': False,
            },
        ),
    ]
