# Generated by Django 4.0.4 on 2022-05-31 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDBRegistrations', '0021_studentgrades_staging'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMakeups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegNo', models.IntegerField()),
                ('RollNo', models.IntegerField()),
                ('sub_id', models.IntegerField()),
                ('SubCode', models.CharField(max_length=10)),
                ('SubName', models.CharField(max_length=50)),
                ('OfferedYear', models.IntegerField()),
                ('Dept', models.IntegerField()),
                ('Credits', models.IntegerField()),
                ('BYear', models.IntegerField()),
                ('BSem', models.IntegerField()),
                ('Grade', models.CharField(max_length=2)),
                ('GP', models.IntegerField()),
                ('Regulation', models.IntegerField()),
                ('AYASBYBS', models.IntegerField()),
            ],
            options={
                'db_table': 'StudentMakeupBacklogsMV',
                'managed': False,
            },
        ),
    ]
