# Generated by Django 4.0.4 on 2022-06-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDBRegistrations', '0022_studentmakeups'),
    ]

    operations = [
        migrations.CreateModel(
            name='MandatoryCredits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Regulation', models.IntegerField()),
                ('Dept', models.IntegerField()),
                ('BYear', models.IntegerField()),
                ('Credits', models.IntegerField()),
            ],
            options={
                'db_table': 'MandatoryCredits',
                'managed': False,
            },
        ),
    ]
