# Generated by Django 4.0.4 on 2022-06-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDBRegistrations', '0023_mandatorycredits'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradePoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Regulation', models.IntegerField()),
                ('Grade', models.CharField(max_length=2)),
                ('Points', models.IntegerField()),
            ],
            options={
                'db_table': 'GradePoints',
                'managed': False,
            },
        ),
    ]
