# Generated by Django 4.0.4 on 2022-06-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDBRegistrations', '0024_gradepoints'),
    ]

    operations = [
        migrations.CreateModel(
            name='RollLists_Staging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegNo', models.IntegerField()),
                ('Dept', models.IntegerField()),
                ('AYear', models.IntegerField()),
                ('BYear', models.IntegerField()),
                ('Cycle', models.IntegerField()),
                ('Regulation', models.IntegerField()),
            ],
            options={
                'db_table': 'RollLists_Staging',
                'managed': False,
            },
        ),
    ]
