# Generated by Django 4.0.4 on 2022-06-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDBRegistrations', '0025_rolllists_staging'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegId', models.IntegerField()),
                ('PreviousGrade', models.CharField(max_length=2)),
                ('UpdatedGrade', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'GradeChallenge',
                'managed': True,
            },
        ),
    ]
