# Generated by Django 4.0.4 on 2022-06-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDBRegistrations', '0027_makeupregistrationsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegulationChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegEventId', models.IntegerField()),
                ('StudentId', models.IntegerField()),
                ('PreviousRegulation', models.IntegerField()),
                ('PresentRegulation', models.IntegerField()),
            ],
            options={
                'db_table': 'RegulationChange',
                'managed': False,
            },
        ),
    ]
