# Generated by Django 4.0.4 on 2022-06-25 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDBRegistrations', '0028_regulationchange'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facultyinfo',
            options={'managed': True},
        ),
    ]
