# Generated by Django 4.0.4 on 2022-06-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDBRegistrations', '0029_alter_facultyinfo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyinfo',
            name='FacultyId',
            field=models.IntegerField(default=100),
        ),
    ]
