# Generated by Django 4.0.4 on 2022-06-25 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDBRegistrations', '0030_facultyinfo_facultyid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facultyinfo',
            old_name='Email',
            new_name='email',
        ),
    ]
