# Generated by Django 4.0.4 on 2022-06-27 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDBRegistrations', '0032_rename_email_facultyinfo_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolllists',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='rolllists_staging',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='studentinfo',
            options={'managed': True},
        ),
    ]
