# Generated by Django 4.0.4 on 2022-06-27 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDBRegistrations', '0033_alter_rolllists_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolllists',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='rolllists_staging',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='studentinfo',
            options={'managed': False},
        ),
    ]
