# Generated by Django 4.0.4 on 2022-06-27 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDBRegistrations', '0035_alter_rolllists_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolllists',
            name='AYear',
        ),
        migrations.RemoveField(
            model_name='rolllists',
            name='BYear',
        ),
        migrations.RemoveField(
            model_name='rolllists',
            name='Dept',
        ),
        migrations.RemoveField(
            model_name='rolllists',
            name='RegNo',
        ),
        migrations.RemoveField(
            model_name='rolllists_staging',
            name='AYear',
        ),
        migrations.RemoveField(
            model_name='rolllists_staging',
            name='BYear',
        ),
        migrations.RemoveField(
            model_name='rolllists_staging',
            name='Dept',
        ),
        migrations.RemoveField(
            model_name='rolllists_staging',
            name='RegNo',
        ),
        migrations.RemoveField(
            model_name='rolllists_staging',
            name='Regulation',
        ),
        migrations.AddField(
            model_name='rolllists',
            name='RegEventId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SupExamDBRegistrations.registrationstatus'),
        ),
        migrations.AddField(
            model_name='rolllists',
            name='Section',
            field=models.CharField(default='NA', max_length=2),
        ),
        migrations.AddField(
            model_name='rolllists',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SupExamDBRegistrations.studentinfo'),
        ),
        migrations.AddField(
            model_name='rolllists_staging',
            name='RegEventId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SupExamDBRegistrations.registrationstatus'),
        ),
        migrations.AddField(
            model_name='rolllists_staging',
            name='Section',
            field=models.CharField(default='NA', max_length=2),
        ),
        migrations.AddField(
            model_name='rolllists_staging',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SupExamDBRegistrations.studentinfo'),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='Address1',
            field=models.CharField(default='a', max_length=150),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='Address2',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='AdmissionYear',
            field=models.IntegerField(default=2015),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='Category',
            field=models.CharField(default='A', max_length=20),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='Dept',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='Gender',
            field=models.CharField(default='M', max_length=10),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='GuardianName',
            field=models.CharField(default='B', max_length=50),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='Phone',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='Regulation',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='email',
            field=models.CharField(default='A', max_length=50),
        ),
        migrations.AlterField(
            model_name='rolllists',
            name='Cycle',
            field=models.IntegerField(choices=[(1, 'PHYSICS'), (2, 'CHEMISTRY')], default=0),
        ),
        migrations.AlterField(
            model_name='rolllists_staging',
            name='Cycle',
            field=models.IntegerField(choices=[(1, 'PHYSICS'), (2, 'CHEMISTRY')], default=0),
        ),
    ]
