# Generated by Django 4.0.4 on 2022-06-27 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDBRegistrations', '0036_remove_rolllists_ayear_remove_rolllists_byear_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolllists',
            name='RegEventId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SupExamDBRegistrations.registrationstatus'),
        ),
        migrations.AlterField(
            model_name='rolllists',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SupExamDBRegistrations.studentinfo'),
        ),
        migrations.AlterField(
            model_name='rolllists_staging',
            name='RegEventId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SupExamDBRegistrations.registrationstatus'),
        ),
        migrations.AlterField(
            model_name='rolllists_staging',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SupExamDBRegistrations.studentinfo'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='Address1',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='Address2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='AdmissionYear',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='Category',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='Dept',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='Gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='GuardianName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='Phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='Regulation',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
