# Generated by Django 4.0.4 on 2022-06-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDBRegistrations', '0037_alter_rolllists_regeventid_alter_rolllists_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='Cycle',
            field=models.IntegerField(choices=[(1, 'PHYSICS'), (2, 'CHEMISTRY')], default=0),
        ),
    ]
