# Generated by Django 4.0.4 on 2022-06-27 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDBRegistrations', '0038_studentinfo_cycle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regulationchange',
            options={'managed': True},
        ),
    ]
