# Generated by Django 4.0.4 on 2022-06-27 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDBRegistrations', '0039_alter_regulationchange_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regulationchange',
            name='StudentId',
        ),
        migrations.AddField(
            model_name='regulationchange',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SupExamDBRegistrations.studentinfo'),
        ),
    ]
