# Generated by Django 4.0.4 on 2022-06-27 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDBRegistrations', '0040_remove_regulationchange_studentid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegulationChange',
        ),
    ]
