# Generated by Django 4.0.4 on 2022-06-27 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDBRegistrations', '0041_delete_regulationchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegulationChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegEventId', models.IntegerField()),
                ('PreviousRegulation', models.IntegerField()),
                ('PresentRegulation', models.IntegerField()),
                ('student', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SupExamDBRegistrations.studentinfo')),
            ],
            options={
                'db_table': 'RegulationChange',
                'managed': True,
            },
        ),
    ]
