# Generated by Django 4.0.4 on 2022-06-27 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDBRegistrations', '0042_regulationchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulationchange',
            name='RegEventId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SupExamDBRegistrations.registrationstatus'),
        ),
    ]
