# Generated by Django 4.0.4 on 2022-06-27 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDBRegistrations', '0043_alter_regulationchange_regeventid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notpromoted',
            options={'managed': True},
        ),
    ]
