# Generated by Django 4.0.4 on 2022-06-27 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDBRegistrations', '0045_alter_notpromoted_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notpromoted',
            options={'managed': True},
        ),
    ]
