# Generated by Django 4.0.4 on 2022-06-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDBRegistrations', '0046_alter_notpromoted_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regulationchange',
            options={'managed': False},
        ),
        migrations.RemoveField(
            model_name='notpromoted',
            name='RegNo',
        ),
        migrations.AddField(
            model_name='notpromoted',
            name='Regulation',
            field=models.IntegerField(default=1),
        ),
    ]
