# Generated by Django 4.0.4 on 2022-06-27 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDBRegistrations', '0047_alter_regulationchange_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notpromoted',
            options={'managed': False},
        ),
    ]
