# Generated by Django 4.0.4 on 2022-06-27 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDBRegistrations', '0048_alter_notpromoted_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotPromoted',
        ),
    ]
