# Generated by Django 4.0.4 on 2022-06-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDBRegistrations', '0049_delete_notpromoted'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotPromoted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AYear', models.IntegerField()),
                ('BYear', models.IntegerField()),
                ('Regulation', models.IntegerField(default=1)),
                ('PoA', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'NotPromoted',
                'managed': True,
            },
        ),
    ]
