# Generated by Django 4.0.4 on 2022-06-27 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDBRegistrations', '0050_notpromoted'),
    ]

    operations = [
        migrations.AddField(
            model_name='notpromoted',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SupExamDBRegistrations.studentinfo'),
        ),
        migrations.AlterField(
            model_name='notpromoted',
            name='Regulation',
            field=models.IntegerField(),
        ),
    ]
