# Generated by Django 4.0.4 on 2022-06-27 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDBRegistrations', '0051_notpromoted_student_alter_notpromoted_regulation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notpromoted',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SupExamDBRegistrations.studentinfo'),
        ),
    ]
