# Generated by Django 4.0.4 on 2022-06-27 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDBRegistrations', '0052_alter_notpromoted_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notpromoted',
            options={'managed': False},
        ),
    ]
