# Generated by Django 4.0.4 on 2022-06-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDBRegistrations', '0053_alter_notpromoted_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='Address2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
