# Generated by Django 4.0.4 on 2022-06-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDBRegistrations', '0054_alter_studentinfo_address2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolllists',
            name='Cycle',
            field=models.IntegerField(choices=[(10, 'PHYSICS'), (9, 'CHEMISTRY')], default=0),
        ),
        migrations.AlterField(
            model_name='rolllists_staging',
            name='Cycle',
            field=models.IntegerField(choices=[(10, 'PHYSICS'), (9, 'CHEMISTRY')], default=0),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='Cycle',
            field=models.IntegerField(choices=[(10, 'PHYSICS'), (9, 'CHEMISTRY')], default=0),
        ),
    ]
