# Generated by Django 4.0.4 on 2022-06-27 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDBRegistrations', '0055_alter_rolllists_cycle_alter_rolllists_staging_cycle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotRegistered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegEventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SupExamDBRegistrations.registrationstatus')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SupExamDBRegistrations.studentinfo')),
            ],
            options={
                'db_table': 'NotRegistered',
                'managed': True,
            },
        ),
    ]
