# Generated by Django 4.0.4 on 2022-06-27 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDBRegistrations', '0056_notregistered'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjects',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='subjects_staging',
            options={'managed': True},
        ),
    ]
