# Generated by Django 4.0.4 on 2022-06-27 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDBRegistrations', '0057_alter_subjects_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='RegEventId',
        ),
        migrations.RemoveField(
            model_name='subjects_staging',
            name='RegEventId',
        ),
    ]
