# Generated by Django 4.0.4 on 2022-06-27 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDBRegistrations', '0058_remove_subjects_regeventid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='RegEventId',
            field=models.ForeignKey(default=31, on_delete=django.db.models.deletion.CASCADE, to='SupExamDBRegistrations.registrationstatus'),
        ),
        migrations.AddField(
            model_name='subjects_staging',
            name='RegEventId',
            field=models.ForeignKey(default=31, on_delete=django.db.models.deletion.CASCADE, to='SupExamDBRegistrations.registrationstatus'),
        ),
    ]
