# Generated by Django 4.0.4 on 2022-06-27 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDBRegistrations', '0059_subjects_regeventid_subjects_staging_regeventid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='droppedregularcourses',
            options={'managed': True},
        ),
    ]
