# Generated by Django 4.0.4 on 2022-06-27 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDBRegistrations', '0061_remove_droppedregularcourses_sub_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='droppedregularcourses',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SupExamDBRegistrations.subjects'),
        ),
    ]
