# Generated by Django 4.0.4 on 2022-06-27 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDBRegistrations', '0062_alter_droppedregularcourses_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects_staging',
            name='RegEventId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SupExamDBRegistrations.registrationstatus'),
        ),
    ]
