# Generated by Django 4.0.4 on 2022-06-27 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDBRegistrations', '0063_alter_subjects_staging_regeventid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='droppedregularcourses',
            name='RegNo',
        ),
        migrations.AddField(
            model_name='droppedregularcourses',
            name='student',
            field=models.ForeignKey(default=2292, on_delete=django.db.models.deletion.CASCADE, to='SupExamDBRegistrations.studentinfo'),
        ),
    ]
