# Generated by Django 4.0.4 on 2022-06-28 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDBRegistrations', '0065_alter_droppedregularcourses_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='RegEventId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SupExamDBRegistrations.registrationstatus'),
        ),
        migrations.CreateModel(
            name='FacultyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Section', models.CharField(default='NA', max_length=2)),
                ('co_ordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_ordinator_facultyInfo', to='SupExamDBRegistrations.facultyinfo')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_facultyInfo', to='SupExamDBRegistrations.facultyinfo')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SupExamDBRegistrations.subjects')),
            ],
            options={
                'db_table': 'FacultyAssignment',
                'managed': True,
            },
        ),
    ]
