# Generated by Django 4.0.4 on 2022-06-28 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDBRegistrations', '0066_alter_subjects_regeventid_facultyassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyassignment',
            name='co_ordinator',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='co_ordinator_facultyInfo', to='SupExamDBRegistrations.facultyinfo'),
        ),
        migrations.AlterField(
            model_name='facultyassignment',
            name='faculty',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_facultyInfo', to='SupExamDBRegistrations.facultyinfo'),
        ),
    ]
