# Generated by Django 4.0.4 on 2022-06-30 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDBRegistrations', '0068_alter_subjects_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notpromoted',
            options={'managed': True},
        ),
    ]
