# Generated by Django 4.0.4 on 2022-06-30 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDBRegistrations', '0069_alter_notpromoted_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notpromoted',
            unique_together={('AYear', 'BYear', 'Regulation', 'student')},
        ),
    ]
