# Generated by Django 4.0.4 on 2022-06-30 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDBRegistrations', '0070_alter_notpromoted_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rolllists',
            unique_together={('student', 'RegEventId')},
        ),
        migrations.AlterUniqueTogether(
            name='rolllists_staging',
            unique_together={('student', 'RegEventId')},
        ),
    ]
