# Generated by Django 3.2.5 on 2021-08-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakeupSummaryStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubName', models.CharField(max_length=100)),
                ('SubCode', models.CharField(max_length=10)),
                ('Dept', models.IntegerField()),
                ('Regulation', models.IntegerField()),
                ('BYear', models.IntegerField()),
                ('Passed', models.IntegerField()),
                ('Failed', models.IntegerField()),
                ('Total', models.IntegerField()),
            ],
            options={
                'db_table': 'MakeupSummaryStatsV',
                'managed': False,
            },
        ),
    ]
