# Generated by Django 3.2.5 on 2021-09-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDB', '0002_makeupsummarystats'),
    ]

    operations = [
        migrations.CreateModel(
            name='DegreeAwardees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegNo', models.IntegerField()),
                ('RollNo', models.IntegerField()),
                ('Dept', models.IntegerField()),
                ('Name', models.CharField(max_length=70)),
                ('PassingYear', models.IntegerField()),
            ],
            options={
                'db_table': 'DegreeAwardees',
                'managed': False,
            },
        ),
    ]
