# Generated by Django 3.2.5 on 2021-11-29 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDB', '0003_degreeawardees'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentadmissionyeardetails',
            table='StudentAdmissionInfoV',
        ),
    ]
