# Generated by Django 3.2.5 on 2022-04-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDB', '0005_facultyinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyInfo1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=70)),
                ('PhoneNumber', models.IntegerField()),
                ('EmailID', models.CharField(max_length=70)),
            ],
            options={
                'db_table': 'FacultyInfo1',
            },
        ),
        migrations.DeleteModel(
            name='FacultyInfo',
        ),
    ]
