# Generated by Django 3.2.5 on 2022-04-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDB', '0006_auto_20220408_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyinfo1',
            name='PhoneNumber',
            field=models.BigIntegerField(),
        ),
    ]
