# Generated by Django 3.2.5 on 2022-04-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDB', '0007_alter_facultyinfo1_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=70)),
                ('PhoneNumber', models.BigIntegerField()),
                ('EmailID', models.CharField(max_length=70)),
            ],
            options={
                'db_table': 'FacultyInfo',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='FacultyInfo1',
        ),
    ]
