# Generated by Django 3.2.5 on 2022-04-13 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SupExamDB', '0009_registrationstatus_studentregistrations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MakeupSummaryStats',
        ),
        migrations.DeleteModel(
            name='RegistrationStatus',
        ),
        migrations.DeleteModel(
            name='StudentRegistrations',
        ),
    ]
