# Generated by Django 3.2.5 on 2021-08-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentExamEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dept', models.IntegerField()),
                ('AYASBYBS', models.IntegerField()),
                ('BYear', models.IntegerField()),
                ('BSem', models.IntegerField()),
            ],
            options={
                'db_table': 'DeptExamEventsMV',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeptExamEventStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dept', models.IntegerField()),
                ('AYASBYBS', models.IntegerField()),
                ('BYear', models.IntegerField()),
                ('BSem', models.IntegerField()),
                ('RegNo', models.IntegerField()),
                ('RollNo', models.IntegerField()),
                ('Name', models.CharField(max_length=70)),
            ],
            options={
                'db_table': 'DeptExamEventStudentsMV',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HeldIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AYear', models.IntegerField()),
                ('ASem', models.IntegerField()),
                ('BYear', models.IntegerField()),
                ('BSem', models.IntegerField()),
                ('AYASBYBS', models.IntegerField()),
                ('HeldIn', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'HeldIn',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProgrammeModel',
            fields=[
                ('PID', models.IntegerField(primary_key=True, serialize=False)),
                ('ProgrammeName', models.CharField(max_length=20)),
                ('ProgrammeType', models.CharField(max_length=10)),
                ('Specialization', models.CharField(max_length=100)),
                ('Dept', models.IntegerField()),
            ],
            options={
                'db_table': 'Departments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentAdmissionYearDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegNo', models.IntegerField()),
                ('RollNo', models.IntegerField()),
                ('Name', models.CharField(max_length=70)),
                ('Dept', models.IntegerField()),
                ('AdmissionYear', models.IntegerField()),
            ],
            options={
                'db_table': 'StudentDetailsV',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentCGPAs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegNo', models.IntegerField()),
                ('AYASBYBS_G', models.IntegerField()),
                ('CGP', models.IntegerField()),
                ('CC', models.IntegerField()),
                ('CGPA', models.FloatField()),
                ('SGP', models.IntegerField()),
                ('SC', models.IntegerField()),
                ('SGPA', models.FloatField()),
            ],
            options={
                'db_table': 'StudentCGPAsMV',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentExamEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegNo', models.IntegerField()),
                ('AYASBYBS', models.IntegerField()),
                ('BYear', models.IntegerField()),
                ('BSem', models.IntegerField()),
                ('IsRegular', models.IntegerField()),
            ],
            options={
                'db_table': 'StudentExamEventsMV',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentGradePoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegNo', models.IntegerField()),
                ('SubCode', models.CharField(max_length=10)),
                ('SubName', models.CharField(max_length=100)),
                ('Grade', models.CharField(max_length=2)),
                ('Credits', models.IntegerField()),
                ('AYASBYBS', models.IntegerField()),
            ],
            options={
                'db_table': 'StudentGradePointsMV',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegNo', models.IntegerField()),
                ('RollNo', models.IntegerField()),
                ('Name', models.CharField(max_length=70)),
            ],
            options={
                'db_table': 'StudentInfo',
                'managed': False,
            },
        ),
    ]
