# Generated by Django 4.0.4 on 2022-08-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BTProgrammeModel',
            fields=[
                ('PID', models.IntegerField(primary_key=True, serialize=False)),
                ('ProgrammeName', models.CharField(max_length=20)),
                ('ProgrammeType', models.CharField(max_length=10)),
                ('Specialization', models.CharField(max_length=100)),
                ('Dept', models.IntegerField()),
            ],
            options={
                'db_table': 'BTProgrammeModel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BTStudentGradePoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegNo', models.IntegerField()),
                ('SubCode', models.CharField(max_length=10)),
                ('SubName', models.CharField(max_length=100)),
                ('Grade', models.CharField(max_length=2)),
                ('Credits', models.IntegerField()),
                ('AYASBYBS', models.IntegerField()),
                ('Type', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'StudentGradePointsMV',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BTStudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegNo', models.IntegerField()),
                ('RollNo', models.IntegerField()),
                ('Name', models.CharField(max_length=70)),
                ('Dept', models.IntegerField()),
            ],
            options={
                'db_table': 'BTStudentInfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DegreeAwardees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegNo', models.IntegerField()),
                ('RollNo', models.IntegerField()),
                ('Dept', models.IntegerField()),
                ('Name', models.CharField(max_length=70)),
                ('PassingYear', models.IntegerField()),
                ('Regulation', models.IntegerField()),
                ('Degree', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'DegreeAwardees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DepartmentExamEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dept', models.IntegerField()),
                ('AYASBYBS', models.IntegerField()),
                ('BYear', models.IntegerField()),
                ('BSem', models.IntegerField()),
            ],
            options={
                'db_table': 'DeptExamEventsMV',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeptExamEventStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dept', models.IntegerField()),
                ('AYASBYBS', models.IntegerField()),
                ('BYear', models.IntegerField()),
                ('BSem', models.IntegerField()),
                ('RegNo', models.IntegerField()),
                ('RollNo', models.IntegerField()),
                ('Name', models.CharField(max_length=70)),
            ],
            options={
                'db_table': 'DeptExamEventStudentsMV',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HeldIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AYear', models.IntegerField()),
                ('ASem', models.IntegerField()),
                ('BYear', models.IntegerField()),
                ('BSem', models.IntegerField()),
                ('AYASBYBS', models.IntegerField()),
                ('HeldInMonth', models.CharField(max_length=10)),
                ('HeldInYear', models.IntegerField()),
            ],
            options={
                'db_table': 'HeldIn',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentAdmissionYearDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegNo', models.IntegerField()),
                ('RollNo', models.IntegerField()),
                ('Name', models.CharField(max_length=70)),
                ('Dept', models.IntegerField()),
                ('AdmissionYear', models.IntegerField()),
            ],
            options={
                'db_table': 'StudentAdmissionInfoV',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentBestGrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegNo', models.IntegerField()),
                ('SubCode', models.CharField(max_length=10)),
                ('SubName', models.CharField(max_length=100)),
                ('Grade', models.CharField(max_length=2)),
                ('Credits', models.IntegerField()),
                ('Creditable', models.IntegerField()),
                ('Category', models.CharField(max_length=10)),
                ('AYASBYBS', models.IntegerField()),
                ('BYBS', models.IntegerField()),
                ('Required', models.IntegerField()),
                ('Order', models.IntegerField()),
            ],
            options={
                'db_table': 'StudentBestGradesV',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentCGPAs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegNo', models.IntegerField()),
                ('AYASBYBS_G', models.IntegerField()),
                ('CGP', models.IntegerField()),
                ('CC', models.IntegerField()),
                ('CGPA', models.FloatField()),
                ('SGP', models.IntegerField()),
                ('SC', models.IntegerField()),
                ('SGPA', models.FloatField()),
            ],
            options={
                'db_table': 'StudentCGPAsMV',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentExamEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegNo', models.IntegerField()),
                ('AYASBYBS', models.IntegerField()),
                ('BYear', models.IntegerField()),
                ('BSem', models.IntegerField()),
                ('IsRegular', models.IntegerField()),
            ],
            options={
                'db_table': 'StudentExamEventsMV',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentFinalCGPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegNo', models.IntegerField()),
                ('CGP', models.IntegerField()),
                ('TotalCredits', models.IntegerField()),
                ('CGPA', models.FloatField()),
            ],
            options={
                'db_table': 'StudentFinalCGPAV',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentFinalSGPAs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegNo', models.IntegerField()),
                ('BYBS', models.IntegerField()),
                ('SGP', models.IntegerField()),
                ('SC', models.IntegerField()),
                ('SGPA', models.FloatField()),
            ],
            options={
                'db_table': 'StudentFinalSGPAsV',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentGradePointsV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegNo', models.IntegerField()),
                ('SubCode', models.CharField(max_length=10)),
                ('SubName', models.CharField(max_length=100)),
                ('Grade', models.CharField(max_length=2)),
                ('Credits', models.IntegerField()),
                ('AYASBYBS', models.IntegerField()),
                ('Type', models.CharField(max_length=10)),
                ('Order', models.IntegerField()),
            ],
            options={
                'db_table': 'StudentGradePointsV',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentSemSubCounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegNo', models.IntegerField()),
                ('BYBS', models.IntegerField()),
                ('SemSubCount', models.IntegerField()),
            ],
            options={
                'db_table': 'StudentSemSubCountsV',
                'managed': False,
            },
        ),
    ]
