# Generated by Django 3.2.5 on 2021-09-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transcripts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentBestGrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegNo', models.IntegerField()),
                ('SubCode', models.CharField(max_length=10)),
                ('SubName', models.CharField(max_length=100)),
                ('Grade', models.CharField(max_length=2)),
                ('Credits', models.IntegerField()),
                ('AYASBYBS', models.IntegerField()),
                ('BYBS', models.IntegerField()),
                ('Required', models.IntegerField()),
            ],
            options={
                'db_table': 'StudentBestGradesV',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentFinalCGPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegNo', models.IntegerField()),
                ('CGP', models.IntegerField()),
                ('CC', models.IntegerField()),
                ('CGPA', models.FloatField()),
            ],
            options={
                'db_table': 'StudentFinalCGPAV',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentFinalSGPAs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegNo', models.IntegerField()),
                ('BYBS', models.IntegerField()),
                ('SGP', models.IntegerField()),
                ('SC', models.IntegerField()),
                ('SGPA', models.FloatField()),
            ],
            options={
                'db_table': 'StudentFinalSGPAsV',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentSemSubCounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegNo', models.IntegerField()),
                ('BYBS', models.IntegerField()),
                ('SemSubCount', models.IntegerField()),
            ],
            options={
                'db_table': 'StudentSemSubCountsV',
                'managed': False,
            },
        ),
    ]
