# Generated by Django 3.2.5 on 2021-09-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transcripts', '0003_degreeawardees'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGradePointsV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegNo', models.IntegerField()),
                ('SubCode', models.CharField(max_length=10)),
                ('SubName', models.CharField(max_length=100)),
                ('Grade', models.CharField(max_length=2)),
                ('Credits', models.IntegerField()),
                ('AYASBYBS', models.IntegerField()),
                ('Type', models.CharField(max_length=10)),
                ('Order', models.IntegerField()),
            ],
            options={
                'db_table': 'StudenGradePointsV',
                'managed': False,
            },
        ),
    ]
