# Generated by Django 3.2.5 on 2021-09-28 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transcripts', '0004_studentgradepointsv'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentgradepointsv',
            table='StudentGradePointsV',
        ),
    ]
